FROM python:3.9-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir --default-timeout=100 -r requirements.txt

ENV FLASK_APP=app.py
ENV FLASK_ENV=development

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
